### ISSUE TITLE
Unsure why it's unresponsive sometimes

### ISSUE THREAD

**Issue by jaanaltosaar** [willwhitney/live-earth-desktop#5]
Love this script, thank you Will. Sometimes if I close the lid on my mac or try to shut down the python script will be unresponsive. Not sure what's causing this, any ideas? I could check to see if there's a way to catch a timeout exception.

**Comment by willwhitney** [comment]
Interesting, I haven't run into that. Is there an error message or anything that could help debug? 

Are you running the current version? A past version had a pretty bad try/except that might eat problems or interrupts.

Are you running it with `launchctl`? I've actually been using recently [BitBar](https://getbitbar.com) so that I get a timestamp in my Mac menu bar (and a GUI way start or stop it).

**Comment by jaanaltosaar** [comment]
Hmm good idea, not sure where to look for the error message. 

Yup using `launchctl` right now and running the latest version.

How are you using it with BitBar? 

(Just installed it, it looks amazing thanks for the pointer :)

**Comment by willwhitney** [comment]
For BitBar I have a file named `goes-east.10m.sh` in my BitBar plugin directory (for me `~/.bitbar`, but you can change it).

The file just has these contents:

```shell
#!/bin/bash
/Users/willwhitney/anaconda3/bin/python /Users/willwhitney/code/live-earth-desktop/goes-east.py
```

Basically you just put any file with a hashbang in that folder, and give it a name that includes how often to run the script (e.g. `script.10s.py` would run every 10 seconds). Here are their docs for all the stuff you can do: https://github.com/matryer/bitbar#writing-plugins

This gives me the little globe and timestamp in my menu bar:

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/597829/49964617-f3be4180-fee8-11e8-91f8-59fb225f7889.png">

**Comment by willwhitney** [comment]
Also I think if you look in `goes-east.plist` it says where stdout/stderr are redirected when you use `launchctl`.

**Comment by jaanaltosaar** [comment]
Awesome, that worked–thanks so much! 🙏 Love this BitBar thing.
