### ISSUE TITLE
Fork & RFP discussion on making beautiful animations

### ISSUE THREAD

**Issue by 100ideas** [willwhitney/live-earth-desktop#6]
Hey Will, thanks for sharing your scripts! I think they are nifty. I am running them myself and forked your repo so I could contribute notes and maybe some code. It would be cool to collaborate with you and/or some of the other folks who have done similar projects - I opened an issue and hard-mentioned some folks hoping they might drop by... https://github.com/100ideas/live-earth-desktop/issues/1

**Comment by willwhitney** [comment]
Thanks for pulling all this together! I'll be keeping an eye on the discussion over there but don't have much background with animation to contribute.
